### PR TITLE
emit errors if hit any circular dependency

### PR DESCRIPTION
**Pull request by huang47**
To address issue #6

### CODE REVIEW

**Comment by backflip** [comment]
Awesome, thanks!

**Comment by backflip** [comment]
On second thought: Should we treat this as a major change (v2.0.0) since it might break existing implementations (which for some reason rely on circular dependencies being silently ignored)?

**Comment by huang47** [comment]
good point, how about making it configurable to be backward compatible ?

```config.checkCircularDependency = true | false ?```

**Comment by backflip** [comment]
Good idea.
I went with the following approach:
* 1.1.0 adds a new option ```ignoreCircularDependencies``` which defaults to true (still using the old behavior)
* 2.0.0 switches its default to ```false``` (emits an error)

**Comment by huang47** [comment]
perfect (y)

**Pull request merged**
